version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: video-processing-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  app:
    build: .
    container_name: video-processing-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
